"""Shared Compras subcategory rules for marketplace imports."""

from __future__ import annotations

import re
from urllib.parse import urlparse

# Ordered: first match wins. Keep ~12–18 categories; Outros last resort.
CATEGORY_RULES: list[tuple[str, str, list[str]]] = [
    (
        "compras-impressao-3d",
        "Impressão 3D",
        [
            r"\b3d\b",
            r"\bender\b",
            r"\bbambu\b",
            r"\bhotend\b",
            r"\bnozzle\b",
            r"\bbico\b.*\b(creality|bambu|ender)\b",
            r"\bfilamento\b",
            r"\bfilament\b",
            r"\bextrusora\b",
            r"\bextruder\b",
            r"\bpei\b",
            r"\bresina\b.*\b(impressora|3d|saturn)\b",
            r"\bcreality\b",
            r"\banycubic\b",
            r"\bsunlu\b",
            r"\bwash\s*&\s*cure\b",
        ],
    ),
    (
        "compras-eletronica",
        "Eletrônica / Maker",
        [
            r"\besp32\b",
            r"\braspberry\b",
            r"\blilygo\b",
            r"\bm5stack\b",
            r"\bheltec\b",
            r"\blora\b",
            r"\bmeshtastic\b",
            r"\boscilloscope\b",
            r"\bosciloscópio\b",
            r"\bmultimeter\b",
            r"\bmultímetro\b",
            r"\balicate amperímetro\b",
            r"\blogic analyzer\b",
            r"\bgeiger\b",
            r"\bthermal (camera|imager|imaging)\b",
            r"\bcâmera térmica\b",
            r"\bflir\b",
            r"\b2\.5gb\b",
            r"\b2\.5g\b",
            r"\bkeystone\b",
            r"\bsata\b",
            r"\bcat6a\b",
            r"\bethernet\b",
            r"\bmanaged switch\b",
            r"\bshort wave antenna\b",
            r"\bam/fm radio\b",
            r"\bsilicon tubing\b",
            r"\bhydroponic\b",
            r"\bph meter\b",
            r"\bppm ec meter\b",
            r"\bperformance memory\b",
            r"\bzimaboard\b",
            r"\bsoldering\b",
            r"\bsolda\b",
            r"\bsolder\b",
            r"\bmáquina de solda\b",
            r"\bmig\b",
            r"\btig\b",
            r"\beletrodo\b",
            r"\barame mig\b",
            r"\bdesolder\b",
            r"\bpcb\b",
            r"\bplaca (de construção|fria)\b",
            r"\bbambulab\b",
            r"\bwater cooling\b",
            r"\bteucer\b",
            r"\bprogrammer\b",
            r"\bwaveshare\b",
            r"\bfnirsi\b",
            r"\baneng\b",
            r"\bqianli\b",
            r"\bzoyi\b",
            r"\bfpga\b",
            r"\btang nano\b",
            r"\bmcb\b",
            r"\bbusbar\b",
            r"\bcircuit breaker\b",
            r"\bvoltmeter\b",
            r"\bdiode\b",
            r"\btransistor\b",
            r"\btuya\b",
            r"\bzigbee\b",
            r"\btermorretráteis?\b",
            r"\bespaguete termo\b",
            r"\bconectores termorretráteis\b",
            r"\bterminais elétricos\b",
            r"\bilhós\b",
            r"\bbaofeng\b",
            r"\brádio\b.*\b(comunicador|walk|uhf|vhf)\b",
            r"\bcomunicador\b",
            r"\bmilliohmimetro\b",
            r"\bspda\b",
            r"\bdetector de câmera\b",
            r"\brastreador gps\b",
            r"\bsinal rf\b",
            r"\bbateria.*cr\d{4}\b",
            r"\bpilha\b",
            r"\bbatteries?\b",
            r"\b18650\b",
            r"\bac adapter\b",
            r"\bbonderite\b",
            r"\btouch-n-prep\b",
            r"\bfonte\b.*\b(atx|600w|raspberry|5v)\b",
            r"\bhd seagate\b",
            r"\bironwolf\b",
            r"\bnas\b",
            r"\bcardputer\b",
            r"\bwire stripper\b",
            r"\bdesencapador\b",
            r"\bcrimpador\b",
            r"\bcabo de rede\b",
            r"\bcat8\b",
            r"\bugreen\b.*\b(cabo|cable)\b",
            r"\bmetering module\b",
            r"\bpower supply\b",
            r"\bswitching power\b",
            r"\bfonte\b",
            r"\bultrasonic cleaner\b",
            r"\bcuba ultrassônica\b",
            r"\btweezers\b",
            r"\btact switch\b",
            r"\bpush button\b",
            r"\brefractory\b",
            r"\bionizing\b",
            r"\bantistatic\b",
            r"\bpogo pin\b",
            r"\bcharge trigger\b",
            r"\bfast charging test\b",
            r"\btin sn\b",
            r"\bindium\b",
            r"\bcopper sheet\b",
            r"\bstainless steel ball\b",
            r"\bto-247\b",
            r"\brectifier\b",
            r"\bdiode\b",
            r"\bwifi\b.*\blora\b",
            r"\brdk\b",
            r"\bcooling case\b",
            r"\bwanptek\b",
            r"\bssd\b",
            r"\bnvme\b",
            r"\bm\.2\b",
            r"\bbattery tester\b",
            r"\bshortwave\b",
            r"\bmulti-band radio\b",
            r"\bretekess\b",
            r"\bhrd-c919\b",
            r"\bmini ?pc\b",
            r"\bfirebat\b",
            r"\bcapacitor\b",
            r"\bstepper motor\b",
            r"\bgearbox\b",
            r"\binverter boost\b",
            r"\bhydro generator\b",
            r"\bmanual.*generator\b",
            r"\brf signal detector\b",
            r"\banti-spy\b",
            r"\bheat shrink\b",
            r"\btermoresist\b",
            r"\beletrofitas?\b",
            r"\bfita el[ée]trica\b",
            r"\brel[ée]\b",
            r"\binterruptor smart\b",
            r"\broteador\b",
            r"\bwi-?fi 6\b",
            r"\bfio de alumínio\b",
            r"\bawg\b",
            r"\bconector el[ée]trico\b",
            r"\bengate r[áa]pido\b",
            r"\bfixed? induction heater\b",
            r"\bmagnetic induction heater\b",
            r"\bferrofluid\b",
            r"\bepomaker\b",
            r"\bmechanical keyboard\b",
            r"\bteclado\b",
            r"\brapid trigger\b",
            r"\bphomemo\b",
            r"\blabel printer\b",
            r"\bmeta quest\b",
            r"\brealidade virtual\b",
            r"\banodiza",
            r"\bnippon nikon\b",
            r"\beletrolítico\b",
            r"\bcarbon fiber\b",
            r"\bmedidor de [âa]ngulo\b",
            r"\bdial indicator\b",
            r"\bprecision meter\b",
            r"\bslide rule\b",
            r"\blogarithmic\b",
        ],
    ),
    (
        "compras-ferramentas",
        "Ferramentas",
        [
            r"\bcnc\b",
            r"\blathe\b",
            r"\bmilling\b",
            r"\bfuradeira\b",
            r"\bparafusadeira\b",
            r"\besmerilhadeira\b",
            r"\blixadeira\b",
            r"\bchave de impacto\b",
            r"\bserra\b",
            r"\bjogo de ferramentas\b",
            r"\bferramentas robust\b",
            r"\bseladoras?\b",
            r"\bcintos teflon\b",
            r"\bhemispherical\b",
            r"\bpinador\b",
            r"\bplasma\b",
            r"\bmicrometer\b",
            r"\bmicrometro\b",
            r"\brelógio comparador\b",
            r"\brotary tool\b",
            r"\bnível a laser\b",
            r"\blaser level\b",
            r"\bmisturador elétrico\b",
            r"\bdesempenadeira\b",
            r"\briscador\b",
            r"\bbroca\b",
            r"\bbrocas?\b",
            r"\bbits?\b",
            r"\bestilete\b",
            r"\balicate\b",
            r"\bpistola de cola\b",
            r"\bespátula\b",
            r"\bsuporte de corte\b",
            r"\brebarbadora\b",
            r"\bmelting furnace\b",
            r"\bforno de fusão\b",
            r"\bvácuo\b",
            r"\bvacuo\b",
            r"\bvacuum\b",
            r"\bbomba\b.*\b(vácuo|vacuo|pressão|pressao|teste)\b",
            r"\bpolishing\b",
            r"\bdspiae\b",
            r"\bstedi\b",
            r"\bworx\b",
            r"\bbingco\b",
            r"\bbosch\b",
            r"\bdewalt\b",
            r"\bhikari\b",
            r"\bhoto\b",
            r"\btoughbuilt\b",
            r"\bthoughbuilt\b",
            r"\bzenite\b",
            r"\bmakita\b",
            r"\bmilwaukee\b",
            r"\bvonder\b",
            r"\bstanley\b",
            r"\bkit de ferramentas\b",
            r"\bcatraca\b",
            r"\btorque (wrench|adapter)\b",
            r"\bdigital torque\b",
            r"\bchain hoist\b",
            r"\bcome along\b",
            r"\bmagnetic (tool|parts)\b",
            r"\bground anchor\b",
            r"\btrampoline anchors?\b",
            r"\bscissor jack\b",
            r"\bmotorcycle lift\b",
            r"\bpry ?bar\b",
            r"\bsocket (tools?|set)\b",
            r"\buniversal socket\b",
            r"\bgator grip\b",
            r"\bdrill (bit|attachment|extension|pump)\b",
            r"\bself priming\b",
            r"\bcountersink\b",
            r"\bdeburring\b",
            r"\bchamfer tool\b",
            r"\bspiral bands?\b",
            r"\bdrum sander\b",
            r"\bmetal shear\b",
            r"\bpipe cutter\b",
            r"\bstrap winder\b",
            r"\bchainsaw attachment\b",
            r"\bpostal scale\b",
            r"\bshipping scale\b",
            r"\bgedore\b",
            r"\btramont\b",
            r"\bmotomil\b",
            r"\bmorsa\b",
            r"\btorno de bancada\b",
            r"\bretificadeira\b",
            r"\brebitador\b",
            r"\bmartelo\b",
            r"\btesoura\b",
            r"\bpun[cç][aã]o\b",
            r"\bpunch\b",
            r"\bguilhotina\b",
            r"\bhex (nuts|cross)\b",
            r"\bscrewdriver\b",
            r"\bchave de fenda\b",
            r"\bdrill bit\b",
            r"\bball plunger\b",
            r"\bspring ball\b",
            r"\bstretch belts?\b",
            r"\bconcrete screw\b",
            r"\bboxer\b.*\b(solda|luva|arame|antirrespingo)\b",
            r"\bluva\b.*\bsolda\b",
            r"\bantirrespingo\b",
            r"\bgabarito\b",
            r"\bwoodwork\b",
            r"\bfixing clip\b",
            r"\bclamping\b",
            r"\bgrampo\b",
            r"\bângulo 90\b",
            r"\babridor de rosca\b",
            r"\bdesoxidante\b",
            r"\bremovedor de ferrugem\b",
            r"\bfita (butílica|dupla face|térmica|termica|teflon|kapton)\b",
            r"\bvhb\b",
            r"\bentretela\b",
            r"\bborracha líquida\b",
            r"\bimpermeabilizante\b",
            r"\bselante\b",
            r"\bcola\b",
            r"\bpipes? expander\b",
            r"\bswaging\b",
            r"\bpottery\b",
            r"\brock tumbler\b",
            r"\bgeometric ruler\b",
            r"\bmeasuring tool\b",
            r"\btool roll\b",
            r"\btool bag\b",
            r"\btool organizer\b",
            r"\bmesa para trabalhos\b",
            r"\bescada\b",
            r"\brolamento\b",
            r"\btorsion spring\b",
            r"\bhex nuts and bolt\b",
            r"\bdepth gauge\b",
            r"\btyre tread\b",
            r"\bdust blower\b",
            r"\bair dust blower\b",
            r"\bcaneta laser\b",
            r"\blaser disparo\b",
            r"\blaser pointer\b",
            r"\bsailrite\b",
            r"\bhandypress\b",
            r"\bgrommets?\b",
        ],
    ),
    (
        "compras-couro-facas",
        "Couro / Facas",
        [
            r"\bleather\b",
            r"\bcouro\b",
            r"\bknife\b",
            r"\bfaca\b",
            r"\bcanivete\b",
            r"\bcutelo\b",
            r"\bkatana\b",
            r"\bespada\b",
            r"\bthinning knife\b",
            r"\bkudo whip\b",
            r"\bself defense\b",
            r"\brifle\b",
            r"\bpistol\b",
            r"\bgunsmith\b",
            r"\bmossberg\b",
            r"\bar-15\b",
            r"\bbrownells\b",
        ],
    ),
    (
        "compras-camping",
        "Camping / Sobrevivência",
        [
            r"\bcamping\b",
            r"\bsobrevivência\b",
            r"\bsurvival\b",
            r"\bpederneira\b",
            r"\bmagnésio\b",
            r"\baventura\b",
            r"\btarpaulin\b",
            r"\blona\b",
            r"\bcolchão inflável\b",
            r"\bbolsa de faraday\b",
            r"\bfaraday\b",
            r"\bmeias de trilha\b",
            r"\btrekking\b",
            r"\bhiking stick\b",
            r"\bwalking stick\b",
            r"\bwalking staff\b",
            r"\brecovery gear\b",
            r"\bratchet straps?\b",
            r"\bgun safe\b",
            r"\boxygen cylinder\b",
            r"\bquechua\b",
            r"\bfósforos?\b",
            r"\bfosforos?\b",
            r"\bstormproof\b",
            r"\buco\b",
        ],
    ),
    (
        "compras-carro",
        "Carro",
        [
            r"\bdash cam\b",
            r"\bddpai\b",
            r"\bcar dvr\b",
            r"\bautomotiv",
            r"\bcarro\b",
            r"\bvolkswagen\b",
            r"\bjetta\b",
            r"\bvw\b",
            r"\brear view\b",
            r"\bcâmera de ré\b",
            r"\bchave geral\b.*\bbateria\b",
            r"\bmanta térmica\b.*\bautomotiv",
            r"\bpara-choque\b",
            r"\bbumper\b",
            r"\bradiador\b",
            r"\bóleo\b.*\bfreio\b",
            r"\bfluido de freio\b",
            r"\bpresilha\b.*\bcarro\b",
            r"\brebite plástico carro\b",
            r"\bfixadores presilha\b",
            r"\bsoundproof\b",
            r"\bdeadener\b",
            r"\bchip de pedal\b",
            r"\bradiadores?\b",
            r"\bparabrisas\b",
            r"\bpara-brisas\b",
            r"\bmicrofiber\b.*\b(car|towel)\b",
            r"\bcar wash\b",
            r"\bcar stereo\b",
            r"\bcar wheel\b",
            r"\btire depth\b",
            r"\bcar (emergency|seat)\b",
            r"\bglass breaker\b",
            r"\bseat belt cutter\b",
            r"\btactical car seat\b",
        ],
    ),
    (
        "compras-audio-video",
        "Áudio / Vídeo",
        [
            r"\bmicrofone\b",
            r"\bmicrophone\b",
            r"\bmaono\b",
            r"\bhollyland\b",
            r"\bfifine\b",
            r"\bsoundbar\b",
            r"\bredragon\b",
            r"\balto-falantes?\b",
            r"\bheadset\b",
            r"\bheadphones?\b",
            r"\bearbuds?\b",
            r"\bearphone\b",
            r"\bmp3\b",
            r"\bprojector\b",
            r"\bprojetor\b",
            r"\bmonitor\b",
            r"\bsceptre\b",
            r"\bultrawide\b",
            r"\bhdmi\b",
            r"\btripé\b",
            r"\bulanzi\b",
            r"\bsony alpha\b",
            r"\bzv-e10\b",
            r"\bstream controller\b",
            r"\bkeycaps?\b",
            r"\biluminador\b",
        ],
    ),
    (
        "compras-iluminacao",
        "Iluminação",
        [
            r"\blanterna\b",
            r"\bflashlight\b",
            r"\bsofirn\b",
            r"\bluz negra\b",
            r"\buv led\b",
            r"\bled cob\b",
            r"\bperfil led\b",
            r"\bfita led\b",
            r"\bbarras? led\b",
            r"\bled (strip|ceiling|pendant|makeup|linear)\b",
            r"\bneon\b.*\bled\b",
            r"\bbedside light\b",
            r"\bceiling lamp\b",
        ],
    ),
    (
        "compras-eletronicos",
        "Eletrônicos",
        [
            r"\bcharger\b",
            r"\bcarregador\b",
            r"\bpower bank\b",
            r"\banker\b",
            r"\busb\b",
            r"\bhdd docking\b",
            r"\bhard drive\b",
            r"\blaptop stand\b",
            r"\bhub\b",
            r"\bgan\b",
            r"\bmovespeed\b",
            r"\bbaseus\b",
            r"\bugreen\b",
            r"\bcabletime\b",
            r"\bessager\b",
            r"\bsmartphone\b",
            r"\bcelular\b",
            r"\bcaterpillar\b",
            r"\bulefone\b",
            r"\brugged\b",
            r"\biPhone\b",
            r"\bpelícula\b",
            r"\bgame console\b",
            r"\b8bitdo\b",
            r"\bcontrole\b",
            r"\bjoypad\b",
            r"\bgamepad\b",
            r"\bmouse\b",
            r"\bmini totem\b",
            r"\bextensão el[eé]trica\b",
            r"\bventilador\b",
            r"\bfan\b",
            r"\bsoprador\b",
            r"\bassoprador\b",
            r"\bsmart tag\b",
            r"\blocalizador\b",
            r"\bfind my\b",
            r"\bgeekom\b",
            r"\basustor\b",
            r"\bqnap\b",
            r"\bsamsung\b",
            r"\bkabum\b",
            r"\bgamemax\b",
            r"\bfechadura digital\b",
            r"\bbiométrica\b",
            r"\bcâmera inteligente\b",
            r"\bintelbras\b",
            r"\blighter\b",
            r"\bbutane\b",
            r"\bairbrush\b",
            r"\bhand exercise\b",
            r"\bwater gun\b",
            r"\bgym bag\b",
            r"\bfitness bag\b",
            r"\bmedicine box\b",
            r"\bpill packaging\b",
        ],
    ),
    (
        "compras-livros",
        "Livros / Hobbies",
        [
            r"\blivro\b",
            r"\blivros\b",
            r"\bmangá\b",
            r"\bmanga\b",
            r"\bfábulas\b",
            r"\bergonomia\b",
            r"\beternauta\b",
            r"\bjunji ito\b",
            r"\bcontos de horror\b",
            r"\bmanual de tecnologia\b",
            r"\bcoup\b",
            r"\bsegunda edição\b.*\bexpans",
            r"\bjogo de tabuleiro\b",
            r"\bboard game\b",
            r"\bcaixa fake\b",
            r"\bporta objetos\b",
            r"\bc[áa]lculo\b",
            r"\bautobiografia\b",
            r"\bmem[óo]rias\b",
            r"\bdynamics of physical\b",
            r"\bperfectionists\b",
            r"\bmechanical design\b",
            r"\bhappyland\b",
            r"\bde que s[ãa]o feitas\b",
            r"\bmetalurgia\b",
            r"\bpol[íi]meros\b",
            r"\bsimula[cç][aã]o virtual\b",
            r"\babraham de moivre\b",
            r"\bportuguese edition\b",
            r"\bastronomia\b",
            r"\bmatem[áa]tica\b",
            r"\bselfish gene\b",
            r"\bwhat we owe the future\b",
            r"\bstructures\b.*\bfall down\b",
            r"\bliftoff\b.*\bspacex\b",
            r"\bignition!\b",
            r"\bignition\b.*\brocket\b",
            r"\bhandyman in-your-pocket\b",
            r"\b12 rules for life\b",
            r"\bhyperbole and a half\b",
            r"\bunlocking the magic\b",
            r"\bdisciplined entrepreneurship\b",
            r"\bsolidworks\b",
            r"\bwinds effects on structures\b",
            r"\baerospace applications\b",
            r"\bcopic\b",
            r"\bpainting (station|mat)\b",
            r"\bballpoint pen\b",
            r"\bretractable ball pens?\b",
        ],
    ),
    (
        "compras-robotica",
        "Robótica / RC",
        [
            r"\brc\b",
            r"\bbulldozer\b",
            r"\bcontrole remoto\b",
            r"\bdrones?\b",
            r"\bquadcopter\b",
            r"\bavião\b",
            r"\bglider\b",
            r"\bhelicopter\b",
            r"\bdrift\b",
            r"\bescavadeira\b",
            r"\blego\b",
            r"\bpokémon\b",
            r"\bpokemon\b",
            r"\buno\b.*\bcartas\b",
        ],
    ),
    (
        "compras-casa",
        "Casa / Cozinha",
        [
            r"\bcasa\b",
            r"\bcozinha\b",
            r"\bcooktop\b",
            r"\bindução\b",
            r"\btorneira\b",
            r"\bexaustor\b",
            r"\bbanheiro\b",
            r"\baquecedor\b",
            r"\bcoletor solar\b",
            r"\bpurificador\b",
            r"\belectrolux\b",
            r"\bgeladeira\b",
            r"\bmicro-ondas\b",
            r"\bmicroondas\b",
            r"\bangry mama\b",
            r"\bgrade de ventilação\b",
            r"\bforno\b",
            r"\bcadeira\b",
            r"\bescritório\b",
            r"\bsalva caixinha\b",
            r"\btomada\b",
            r"\bwindow cleaning\b",
            r"\bcleaning robot\b",
            r"\brobó limpa\b",
            r"\bweather\b",
            r"\bestação meteorológica\b",
            r"\bbento\b",
            r"\bmonbento\b",
            r"\bsoap\b",
            r"\bapron\b",
            r"\bjardim\b",
            r"\bsementes?\b",
            r"\bmelancia\b",
            r"\bkitchenaid\b",
            r"\bbatedeira\b",
            r"\bmultiprocessador\b",
            r"\bair fryer\b",
            r"\bfritadeira\b",
            r"\bmarmita el[ée]trica\b",
            r"\blava[- ]?louças?\b",
            r"\bassento sanitário\b",
            r"\bbid[eê]\b",
            r"\bchá\b",
            r"\bcha preto\b",
            r"\bbiombo\b",
            r"\bcortina\b",
            r"\bdivisor\b",
            r"\bencosto\b",
            r"\balmofada\b",
            r"\bpanela\b",
            r"\bpolishop\b",
            r"\bpotato ricer\b",
            r"\btoilet paper holder\b",
            r"\btowel holder\b",
            r"\bbalança\b",
            r"\btimemore\b",
            r"\bextintora?\b",
            r"\bfireball\b",
            r"\bair conditioner\b",
            r"\bar condicionado\b",
            r"\bbird feeder\b",
            r"\bjacinox\b",
            r"\baço inox\b",
            r"\becoterm\b",
            r"\btijolo ecol",
            r"\bcaneca\b",
            r"\bstar wars\b",
            r"\bcookware\b",
            r"\bnonstick\b",
            r"\bthermos\b",
            r"\bcarafe\b",
            r"\bmoving blankets?\b",
            r"\bspray bottle\b",
            r"\bweighing bottle\b",
            r"\bpycnometer\b",
            r"\bphosphoric acid\b",
            r"\bsubmersible pump\b",
            r"\bfountain pump\b",
            r"\bplant food\b",
            r"\bseedling sponges?\b",
        ],
    ),
    (
        "compras-organizacao",
        "Organização",
        [
            r"\borganizador\b",
            r"\bpainel\b.*\bferrament",
            r"\bgaveteiro\b",
            r"\bcarrinho ferramentas\b",
            r"\barmário para ferramentas\b",
            r"\bbancada\b",
            r"\bfercar\b",
            r"\babraçadeiras?\b",
            r"\bpresilha\b",
            r"\bclipes? de cabo\b",
            r"\bcable (ties|organizer|management|winder)\b",
            r"\borganizador de (fios|cabos)\b",
            r"\bfood storage\b",
            r"\bcontainer\b",
            r"\bprint in place clamp\b",
            r"\bcable strap\b",
        ],
    ),
    (
        "compras-roupas",
        "Roupas / Acessórios",
        [
            r"\bmacacão\b",
            r"\bjaleco\b",
            r"\buniforme\b",
            r"\bluvas?\b",
            r"\bwork gloves\b",
            r"\btactical ratchet belt\b",
            r"\bgun belt\b",
            r"\bcrocs\b",
            r"\bsandália\b",
            r"\bchinelo\b",
            r"\btênis\b",
            r"\bshorts?\b",
            r"\bcamisa\b",
            r"\bmeias?\b",
            r"\bestojo\b",
            r"\bsestini\b",
            r"\brelógio\b",
            r"\bg-shock\b",
            r"\bcasio\b",
            r"\borient\b",
            r"\btechnos\b",
            r"\bpulseira\b",
            r"\banel\b",
            r"\bring\b",
            r"\btungsten\b",
            r"\bperfume\b",
            r"\beau de parfum\b",
            r"\bepi\b",
            r"\bansell\b",
            r"\balphatec\b",
            r"\bcampo cirurgico\b",
            r"\bbrim\b",
        ],
    ),
    (
        "compras-esporte",
        "Esporte / Outdoor",
        [
            r"\bpesca\b",
            r"\bmolinete\b",
            r"\bvara\b",
            r"\bacademia\b",
            r"\bcorrida\b",
            r"\btreino\b",
            r"\bmoto\b",
            r"\bbike\b",
            r"\besportiv",
            r"\bairsoft\b",
            r"\bmira\b",
        ],
    ),
    (
        "compras-pet",
        "Pet",
        [
            r"\bgato\b",
            r"\bgatos\b",
            r"\bcachorro\b",
            r"\bpet\b",
            r"\bração\b",
            r"\bracao\b",
            r"\bfresh meat\b",
            r"\bplayground gato\b",
            r"\bprateleiras para gatos\b",
            r"\bpate gato\b",
            r"\bcat dog food\b",
        ],
    ),
    (
        "compras-higiene",
        "Higiene / Cuidados",
        [
            r"\bshampoo\b",
            r"\bbálsamo\b",
            r"\bbalsamo\b",
            r"\bbarba\b",
            r"\bhidratante\b",
            r"\bkit barba\b",
            r"\brazors?\b",
            r"\bpasta sabão\b",
            r"\bdesengraxante\b",
            r"\bbolsa térmica gel\b",
            r"\bairbrush\b.*\bpele\b",
            r"\boxigênio injector\b",
            r"\bmelatonina\b",
            r"\bgomas\b.*\b(fini|dr good)\b",
        ],
    ),
    (
        "compras-alimentos",
        "Alimentos / Bebidas",
        [
            r"\bwhisky\b",
            r"\bcerveja\b",
            r"\bvinho\b",
            r"\brefrigerante\b",
            r"\bpepsi\b",
            r"\bjack daniel\b",
            r"\bjim beam\b",
            r"\badoçante\b",
            r"\bavelã\b",
            r"\bpílulas felicidade\b",
            r"\bbalas\b",
            r"\bchá\b",
            r"\bmoncloa\b",
            r"\bketchup\b",
            r"\bmaionese\b",
            r"\bheinz\b",
            r"\bkewpie\b",
        ],
    ),
    (
        "compras-servicos",
        "Serviços / Lojas",
        [
            r"amazon\.com\s*:",
            r"^amazon\.com\.br\b",
            r"\bamazon quase novo\b",
            r"\baws (lambda|serverless|compute)\b",
            r"\byan cui\b",
            r"\btudo pra você\b",
            r"\bmakesupply\b",
            r"\bofertas\b",
            r"\bpromobit\b",
            r"\bpelando\b",
            r"\bgrabr\b",
            r"\bvpn\b",
            r"\bmullvad\b",
            r"\bgeojson\b",
            r"\bcraiyon\b",
            r"\bdall-e\b",
            r"\bgithub pages\b",
            r"\bhackaday\b",
            r"\betsy\b",
            r"\bshoptime\b",
            r"\bsubmarino\b",
            r"kabum",
            r"\bsas\b",
            r"\bcurso\b",
            r"\boficina\b",
            r"\bdeploy\b",
            r"\bextrato irpf\b",
            r"\bgenshin\b",
            r"\bepidemic sound\b",
            r"\breact native\b",
            r"\bcalendar strip\b",
            r"\bno-code\b",
            r"\bsem codar\b",
            r"\blogo design\b",
            r"\bwizyakuza\b",
            r"\balch shop\b",
            r"\bgarimpool\b",
            r"\bgn automação\b",
            r"samsung\.com",
            r"\bcalculadora\b",
            r"\bbruno om\b",
            r"\bautoentusiastas\b",
            r"\bsonoran desert\b",
            r"\bcrkd\b",
            r"\bterramax\b",
            r"\bnintendo\b",
            r"\beshop-prices\b",
            r"\bgame guide\b",
            r"\btopdon\b",
            r"\bindependência ou morte\b",
            r"\bprincesa isabel\b",
            r"\bsomos a revolução\b",
            r"\brobocore\b",
            r"\blearn:\b",
            r"\bhow-to content\b",
            r"\bloom\b",
            r"\bvideo messaging\b",
            r"技嘉",
            r"淘宝",
            r"\bmelhor envio\b",
            r"\bmycrypto\b",
            r"\bnogi art\b",
            r"\boaleil",
            r"\bopenai\b",
            r"\bpoeta\b",
            r"\bprime video\b",
            r"\btrilogy games\b",
            r"\bfábrica da china\b",
            r"\breactive resume\b",
            r"\brecarga club\b",
            r"\brtg especial",
            r"\bsanago\b",
            r"\beast of nowhere\b",
            r"\bsgpweb\b",
            r"\bstremio\b",
            r"\btailwind\b",
            r"\btime tracking\b",
            r"\bdareboost\b",
            r"\bwhatsapp\b",
            r"\bwordpress\b",
            r"\b淘宝\b",
            r"\bglobal store\b",
            r"\bmauser\b",
            r"\bmodern firearms\b",
            r"\bltt\b",
            r"\bshadow sponsor\b",
            r"\bprintables\b",
            r"\bmakerworld\b",
            r"\bthingiverse\b",
            r"royal shop",
            r"\bgoma tragacanto\b",
            r"\bbrunir\b",
        ],
    ),
]

STORE_HOSTS = [
    ("AliExpress", ("aliexpress.com", "aliexpress.us", "aliexpress.ru")),
    ("Mercado Livre", ("mercadolivre.com.br", "mercadolibre.com", "mercadolibre.com.ar", "produto.mercadolivre.com.br")),
    ("Shopee", ("shopee.com.br", "shopee.com")),
    # .com.br before .com so BR does not match EUA
    ("Amazon", ("amazon.com.br",)),
    ("Amazon EUA", ("amazon.com", "amzn.to")),
]


def detect_store(url: str) -> str:
    host = (urlparse(url).hostname or "").lower().removeprefix("www.")
    for name, hosts in STORE_HOSTS:
        if any(host == h or host.endswith("." + h) for h in hosts):
            return name
    return "Outros"


def categorize(text: str) -> tuple[str, str]:
    low = (text or "").lower()
    for cat_id, cat_title, patterns in CATEGORY_RULES:
        for pat in patterns:
            if re.search(pat, low, flags=re.I):
                return cat_id, cat_title
    return "compras-outros", "Outros"


def all_category_defs() -> list[dict]:
    seen = []
    for cat_id, cat_title, _ in CATEGORY_RULES:
        seen.append({"id": cat_id, "title": cat_title, "section": "compras"})
    seen.append({"id": "compras-outros", "title": "Outros", "section": "compras"})
    return seen
